### ISSUE TITLE
Access to a private reference?

### ISSUE THREAD

**Issue by blackbox-tech** [martong/access_private#12]
Awesome little header, is there a way to access a private member that is a reference?

It's not listed as a limitation, but I could not find a test for it. 

I did some experiments in g++ but I got some compilation errors, for example:
```cpp

struct A {
public:
    A() : foo(99), bar(foo) {}
private:
    int foo;
    int& bar;
};

ACCESS_PRIVATE_FIELD(A, int, bar)  // error: cannot create pointer to reference member
ACCESS_PRIVATE_FIELD(A, int&, bar) // error: cannot declare pointer to 'using Alias_PrivateAccessTag0 = int&' {aka 'int&'}

int& x = access_private::bar(a);
```

**Comment by blackbox-tech** [comment]
I guess the answer is you can't as bar may not use any storage (like here is an alias for foo), so you can't uses its address to specialize the template?

**Comment by martong** [comment]
Hey, thank you for bringing this up. I believe that your conclusion is correct, a pointer to reference is illegal in C++, thus we cannot instantiate the "getter" template. I'll update the limitations section.
