### ISSUE TITLE
access private overloaded function

### ISSUE THREAD

**Issue by TianBo-Timothy** [martong/access_private#2]
Hi Martong,
I am using access_private for testing. I noticed that when I try to access private overloaded function, a compile error will be issued as follows:
```
access_private.hpp:52:59: error: decltype cannot resolve address of overloaded function
       template struct private_access<decltype(&Class::Name), &Class::Name,

```
The class I was trying to access looks like:
```
class Foo
{
public:
    void print();
private:
    void print(int n);
};
```
In my test code, I declared 
```
ACCESS_PRIVATE_FUN(Foo, void(int), print)
```
to access void Foo::print(int n). It was this line that made the compiler complain.

Any suggestion?

**Comment by martong** [comment]
Hi, 

Thanks for reporting this issue and sorry for the late answer.
I would have a solution, however that would work only on GCC. Clang does not comply to the standard, see:
https://bugs.llvm.org/show_bug.cgi?id=35647

**Comment by leeqx** [comment]
how to use in gcc,for your solution?can you show me the example with the test code
