### ISSUE TITLE
ACCESS_PRIVATE_FUN doesn't work with Microsoft's compiler

### ISSUE THREAD

**Issue by ujhazib** [martong/access_private#4]
Hi!

The following example breaks on Visual Studio:

```
class A {
	int m_i = 3;
	void a() {}
};
ACCESS_PRIVATE_FIELD(A, int, m_i)
ACCESS_PRIVATE_FUN(A, void(), a);
```

**Comment by martong** [comment]
Hi!

Thanks for reporting the issue!
However, looks like Microsoft does not follow the C++ standard (C++11 Standard / 14.7.2 (Explicit instantiation) / 12).

> The usual access checking rules do not apply to names used to specify explicit instantiations. [Note: In particular, the template arguments and names used in the function declarator (including parameter types, return types and exception specifications) may be private types or objects which would normally not be accessible and the template may be a member template or member function which would not normally be accessible. —endnote]

The below code compiles both on recent Clang and GCC.
```
template <typename PtrType, PtrType PtrValue, typename TagType>
struct private_access {
  friend PtrType get(TagType) { return PtrValue; }
};

class Foo
{
  void print0(int);
  void print();
  void print(int);
};

using A = void(int);
using B = A Foo::*;
struct Tag {};
template struct private_access<B, &Foo::print0, Tag>;// OK
//template struct private_access<B, &Foo::print, Tag>; // ERROR in Clang, OK in GCC

int main() { return 0; }
```

**Comment by martong** [comment]
http://rextester.com/BKQEDX52548

**Comment by ujhazib** [comment]
Yeap, I searched for this afterwards and I forgot to write here the conclusion, sorry for it. I see some compilers lack this ability, even some version of GCC had issues with it.

**Comment by martong** [comment]
Nevertheless, I reported the bug to Microsoft via email. I hope we will get an URL to the bug soon, and perhaps later a fix too.
