### ISSUE TITLE
Is it possible to get the address of a static member function?

### ISSUE THREAD

**Issue by mcleary** [martong/access_private#5]
My first guess is no because the actual declaration of the `call_private_static` class uses the forward mechanism, but never hurts to ask if this is possible with this awesome library.
```c++
class A {
    static void f();
};
ACCESS_PRIVATE_STATIC_FUN(A, void(), f);
void func() {
    &call_private_static::A::f;
}
```
I get

```c++
In function 'void func()':

<source>:159:2: error: statement cannot resolve address of overloaded function

  &call_private_static::A::f;
```

My test is here: https://godbolt.org/z/00Z55P

**Comment by martong** [comment]
This library does not provide an API to access the address of a static function, however it could be extended in such a way. My primary focus was to provide an easy to use lib for the most common case which is calling that function.

Nevertheless, you can easily get the address by doing the explicit template instantiation manually:
```
#include <cassert>
#include <iostream>
class A { static void f() { std::cout << "Hello\n"; } };

using Signature = void();

template <Signature* PtrValue> struct private_access {
  friend Signature* get() { return PtrValue; }
};

Signature* get();

template struct private_access<&A::f>;

int main() {
  Signature* fp = get(); // get a function pointer to the private f
  fp(); // call it, prints "Hello"
}
```

**Comment by mcleary** [comment]
Thanks for this, looks really helpful.
