### ISSUE TITLE
ill-formed technique used

### ISSUE THREAD

**Issue by schaumb** [martong/access_private#7]
[This C++ std issue](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2118) says: 
> Stateful metaprogramming via friend injection

> techniques should be ill-formed

The `::private_access_detail::private_access<...>` template class implements a friend function `get()`, which used after class definition.

I think it is worth a line in the README, beside the `#define private public` caveat.

**Comment by martong** [comment]
Thanks, I've added that as a note to the README.
Do you know if the referenced issue has been ever fixed in any later standards? If yes, could you please provide the reference to the specific paragraph in the standard?

**Comment by schaumb** [comment]
I cannot find any progress on this issue. [[1]](https://wg21.cmeerw.net/cwg/issue2118) [[2]](https://stackoverflow.com/questions/44267673/is-stateful-metaprogramming-ill-formed-yet) [[3]](https://ledas.com/post/857-how-to-hack-c-with-templates-and-friends/).
The main reason is that `the mechanism for prohibiting them is as yet undetermined.`

**Comment by yuantailing** [comment]
I don't think it's **stateful** metaprogramming.

"Stateful metaprogramming" is a much more complex technique, such as [[2]](https://stackoverflow.com/questions/44267673/is-stateful-metaprogramming-ill-formed-yet) and [[4]](https://b.atch.se/posts/non-constant-constant-expressions/), where the implementation of the friend function is overwritten multiple times. In [[2]](https://stackoverflow.com/questions/44267673/is-stateful-metaprogramming-ill-formed-yet), it implements a stateful constexpr **counter** of which `static_assert(counter() != counter(), "")`.

In my opinion, implementing friend functions in templates is a standard technique, if you don't overwrite the friend function.

**Comment by schaumb** [comment]
At the std cwg issue [[1]](https://wg21.cmeerw.net/cwg/issue2118), the definition of Stateful metaprogramming is the following:

> Defining a friend function in a template, then referencing that function later provides a means of capturing and retrieving metaprogramming state. This technique is arcane and should be made ill-formed.

When the `private_access<>` template class defines the `friend get()` function, and after in `call_private::` exactly this technique is used.
