### ISSUE TITLE
abort protected or private

### ISSUE THREAD

**Issue by fox-wangguodong** [martong/access_private#9]
i can use ACCESS_PRIVATE_FIELD to access private member，but how can i access protected or private method ?

**Comment by schaumb** [comment]
Hi @fox-wangguodong,

Protected members/functions accessibility are the same as privates.

```cpp
ACCESS_PRIVATE_FUN(Class, int(), test1);
ACCESS_PRIVATE_FUN(Class, void(int&, double), test2);
ACCESS_PRIVATE_FUN(Class, const char*() const, hello);
```
```cpp
Class p;
int a;
call_private::test1(p);
call_private::test2(p, a, 2.0);
call_private::hello(p);
```

You can [try it](https://godbolt.org/z/MohYxW8oT).

The `README.md` is not mentions `ACCESS_PRIVATE_FUN` macro and `call_private` namespace, and not mentions the default arguments in the limitation either.

**Comment by martong** [comment]
Thanks guys for the feedback! I've updated the readme.
